### ISSUE TITLE
Alternate Time Step Segments issues in meta-model, Ex: PS3_6280_6230

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/meta_model#25]
Gen Info has timestep 
- Ex: `input/param/river/vahydro_2022/gen_info_rseg.csv`

- Reran from seg `PS3_6280_6230`
   - no luck 
- Reran from upstream seg into temp directory
```
cd /opt/model/p6/vadeq
rseg=PS3_6161_6280
nohup $META_MODEL_ROOT/run_model $rmodel $rscenario $rseg /opt/model/p6/vadeq/tmp/scratch/6155 river &
```

### Next to try
- run each step 1 by 1 

```
cd /opt/model/p6/vadeq
rseg=PS3_6161_6280
nohup $META_MODEL_ROOT/run_model $rmodel $rscenario $rseg /opt/model/p6/vadeq/tmp/scratch/6155 river prep &
nohup $META_MODEL_ROOT/run_model $rmodel $rscenario $rseg /opt/model/p6/vadeq/tmp/scratch/6155 river run 08 &
nohup $META_MODEL_ROOT/run_model $rmodel $rscenario $rseg /opt/model/p6/vadeq/tmp/scratch/6155 river run 09 &
less +F nohup.out
```

_Originally posted by @jdkleiner in https://github.com/HARPgroup/HARParchive/issues/771#issuecomment-1474288064_

**Comment by rburghol** [comment]
Another case for our edification @jdkleiner .  Seems to be a model computation error due to the original 60 minute timestep?
- Ran: 
- Got errors:
   - `File "/home/rob/.local/lib/python3.8/site-packages/HSP2/HYDR.py", line 122, in hydr`
   - `errors = _hydr_(ui, ts, COLIND, OUTDGT, rchtab, funct, Olabels, OVOLlabels)                  # run reaches simulation code`
   - `ZeroDivisionError: division by zero`
- Changed `input/param/river/vahydro_2022/gen_info_rseg.csv`
   - From: `YP3_6472_6470,3,0,S,60`
   - To: `YP3_6472_6470,3,0,S,15` 
   - Reran: `

**Comment by jdkleiner** [comment]
Here's another finding, might be part of the problem? 

Currently running step 10 produces a PS3_6161_6280_OVOL3.csv file in the following format: 
```
rseg=PS3_6161_6280
$META_MODEL_ROOT/run_model $rmodel $rscenario $rseg /opt/model/p6/vadeq/tmp/scratch/jk_test river run 10

1984-01-01 00:15:00 UTC,14.9877672195435
1984-01-01 00:30:00 UTC,11.5635957717896
1984-01-01 00:45:00 UTC,9.0616340637207
1984-01-01 01:00:00 UTC,7.21803331375122
1984-01-01 01:15:00 UTC,5.76765918731689
1984-01-01 01:30:00 UTC,4.78203153610229
1984-01-01 01:45:00 UTC,4.15933418273926
1984-01-01 02:00:00 UTC,3.64535689353943
1984-01-01 02:15:00 UTC,5.74062776565552
1984-01-01 02:30:00 UTC,10.4613332748413
```

Specifying the string as minute produces a PS3_6161_6280_OVOL3.csv file in the following format: 
```
Rscript $META_MODEL_ROOT/scripts/wdm/csv_export_wdm_format.R PS3_6161_6280_hydr.csv PS3_6161_6280_OVOL3.csv OVOL3 minute

1984,1,1,0,15,14.9877672195435
1984,1,1,0,30,11.5635957717896
1984,1,1,0,45,9.0616340637207
1984,1,1,1,0,7.21803331375122
1984,1,1,1,15,5.76765918731689
1984,1,1,1,30,4.78203153610229
1984,1,1,1,45,4.15933418273926
1984,1,1,2,0,3.64535689353943
1984,1,1,2,15,5.74062776565552
1984,1,1,2,30,10.4613332748413
```

**Comment by jdkleiner** [comment]
I think that makes sense, does that averaging/summing then happen on the "link" step of the meta model?

**Comment by rburghol** [comment]
@jdkleiner 
> does that averaging/summing then happen on the "link" step of the meta model?
Unfortunately no, since we realized that the loading of the downstream inflow WDMs must occur at the end of the run phase in order for the sediment stuff (hard-wired in) runs, so we've struggled with that conceptually since it *should* be where you suggest.

Anyhow, it goes here: `models/hsp2_cbp6/river/run/10_hydr_to_wdm`
in the call to `Rscript $META_MODEL_ROOT/scripts/wdm/csv_export_wdm_format.R  $csvfile $wdmcsv $col string`

I'm gonna give that a looksee unless you want to tackle it?  I am running Potomac sims for the cbp-6.1 and of course it also suffers from this problem.

**Comment by jdkleiner** [comment]
@rburghol I'd say go ahead and give it a looksee if you think you've got a good handle on it. And holler if there's anything you need on my end!

**Comment by jdkleiner** [comment]
@rburghol Excellent work! I'll go ahead and kick off a base model run!

**Comment by jdkleiner** [comment]
@rburghol Model looks good! `PS3_6280_6230` completed successfully for hsp2_2022 run
